[project]
name = "gfont-woff2-downloader"
version = "0.1.0"
description = "Download woff2 font files from google."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
]

